[package]
name = "zed-just-ls"
version = "0.1.1"
edition = "2024"
repository = "https://github.com/sectore/zed-just-ls"
license = "MIT"

[lib]
path = "src/just.rs"
crate-type = ["cdylib"]

[dependencies]
zed_extension_api = "0.4.0"
